spring.application.name=test-resource-server

server.port=${env.server.port}

auth-server.path=${env.auth-server.path}
auth-server.oauth2.path=${auth-server.path}/oauth2
auth-server.oauth2.token-path=${auth-server.oauth2.path}/token
auth-server.oauth2.jwks-path=${auth-server.oauth2.path}/jwks

authorize-http-requests=/actuator/**,/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${auth-server.oauth2.jwks-path}
