package io.github.tbondetti.testresourceserver.core.exception;

public enum ResourceServerErrorCode {

    UNAUTHORIZED,
    FORBIDDEN,

    PRODUIT_NOM_REQUIRED,
    PRODUIT_NOM_TOO_SHORT,
    PRODUIT_NOM_TOO_LONG,

    NUMERO_GENERATION_FAILED,

    PRODUIT_PRIX_MUST_NOT_BE_NULL,
    PRODUIT_PRIX_MUST_BE_POSITIVE,
    PRODUIT_PRIX_HAS_TOO_MANY_DECIMALS,

    PRODUIT_NOT_FOUND,

    COMMANDE_EMAIL_CLIENT_REQUIRED,
    COMMANDE_EMAIL_CLIENT_TOO_LONG,
    COMMANDE_EMAIL_CLIENT_INVALID,

    COMMANDE_NOT_FOUND,
    COMMANDE_NUMEROS_PRODUITS_ARE_REQUIRED,

    VALIDATION_ERROR
}
